In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [2]:
dataset=pd.read_csv(r"C:\Users\beher\OneDrive\Desktop\ML\classification\logit classification.csv")

In [3]:
dataset.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
x=dataset.drop(['User ID','Gender','Purchased'],axis=1)

In [5]:
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [6]:
y=dataset['Purchased']

In [7]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
rf=RandomForestClassifier(random_state=0,max_depth=3,criterion='log_loss')
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [16]:
ac=accuracy_score(y_test,y_pred)
ac

0.95

In [17]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[55  3]
 [ 1 21]]

In [18]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.98      0.95      0.96        58
           1       0.88      0.95      0.91        22

    accuracy                           0.95        80
   macro avg       0.93      0.95      0.94        80
weighted avg       0.95      0.95      0.95        80

In [19]:
bias=rf.score(x_train,y_train)
bias

0.915625

In [20]:
var=rf.score(x_test,y_test)
var

0.95